/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.29).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.sap.lm.sl.spfi.operations.client;

import com.sap.lm.sl.spfi.operations.client.model.SaaSFulfillment;
import com.sap.lm.sl.spfi.operations.client.model.Status;

public interface ISpfiOperationsClient {
    // fetch details of a received notification for a fulfillment request 

    // Get details of a notified fulfillment request from SAP Unified Provisioning engine based on notification id.
    SaaSFulfillment resolvetFulfillment(String xSapSpfiNotifcationId) throws SpfiClientException;

    // Post the status of a command execution by the Saas provider back to unified provisioning
    void updateFulfillment(String xSapSpfiNotifcationId, Status status) throws SpfiClientException;
}
