/*
 * SaaS Provider Fulfillment Interface API.
 * * SPFI API Design based on \"Notification\" and \"Resolve\" approach * SPFI following the design of Notified Command (write,update,delete,...)and Query(read) Segregation  * It consists of a set of APIs to be invoked/called by SaaS Providers. * This is the lite version of SFPI focuses only Frontrunner applications(Ex:ICEA Bundles).  * Scope limited to tenants in the first release,but extensible to add further entities. 
 *
 * OpenAPI spec version: 1.0.2-sap-dev-internal
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.lm.sl.spfi.operations.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * ActivateContext
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-03-28T15:44:05.391Z[GMT]")
public class ActivateContext implements OneOfSaaSFulfillmentDetails {
  @SerializedName("tenant")
  private Tenant tenant = null;

  @SerializedName("customer")
  private Customer customer = null;

  @SerializedName("initialUsers")
  private List<User> initialUsers = null;

  @SerializedName("contractValidity")
  private ContractValidity contractValidity = null;

  @SerializedName("additionalProperties")
  private AdditionalProperties additionalProperties = null;

  @Schema(description = "")
  public AdditionalProperties getAdditionalProperties() {
    return additionalProperties;
  }

  public void setAdditionalProperties(AdditionalProperties additionalProperties) {
    this.additionalProperties = additionalProperties;
  }

  public ActivateContext additionalProperties(AdditionalProperties additionalProperties) {
    this.additionalProperties = additionalProperties;
    return this;
  }


  public ActivateContext tenant(Tenant tenant) {
    this.tenant = tenant;
    return this;
  }

   /**
   * Get tenant
   * @return tenant
  **/
  @Schema(description = "")
  public Tenant getTenant() {
    return tenant;
  }

  public void setTenant(Tenant tenant) {
    this.tenant = tenant;
  }

  public ActivateContext customer(Customer customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @Schema(description = "")
  public Customer getCustomer() {
    return customer;
  }

  public void setCustomer(Customer customer) {
    this.customer = customer;
  }

  public ActivateContext initialUsers(List<User> initialUsers) {
    this.initialUsers = initialUsers;
    return this;
  }

  public ActivateContext addInitialUsersItem(User initialUsersItem) {
    if (this.initialUsers == null) {
      this.initialUsers = new ArrayList<User>();
    }
    this.initialUsers.add(initialUsersItem);
    return this;
  }

   /**
   * Get initialUsers
   * @return initialUsers
  **/
  @Schema(description = "")
  public List<User> getInitialUsers() {
    return initialUsers;
  }

  public void setInitialUsers(List<User> initialUsers) {
    this.initialUsers = initialUsers;
  }

  // added contractValidity - upsl-340
  @Schema(description = "")
  public ContractValidity getContractValidity() {
    return contractValidity;
  }

  public void setContractValidity(ContractValidity contractValidity) {
    this.contractValidity = contractValidity;
  }

  public ActivateContext contractValidity(ContractValidity contractValidity) {
    this.contractValidity = contractValidity;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivateContext activateContext = (ActivateContext) o;
    return Objects.equals(this.tenant, activateContext.tenant) &&
        Objects.equals(this.customer, activateContext.customer) &&
        Objects.equals(this.initialUsers, activateContext.initialUsers) &&
        Objects.equals(this.contractValidity, activateContext.contractValidity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenant, customer, initialUsers, contractValidity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivateContext {\n");
    
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    initialUsers: ").append(toIndentedString(initialUsers)).append("\n");
    sb.append("    contractValidity: ").append(toIndentedString(contractValidity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
