/*
 * SaaS Provider Fulfillment Interface API.
 * * SPFI API Design based on \"Notification\", \"Resolve\" and \"Status\" approach * SPFI following the design of Notified Command (write,update,delete,...) and Query (read) Segregation  * It consists of a set of APIs to be invoked/called by SaaS Providers. * This is the lite version of SFPI focuses only Frontrunner applications (Ex:ICEA Bundles).  * Scope limited to tenants in the first release, but extensible to add further entities. 
 *
 * OpenAPI spec version: 1.0.6-sap-dev-internal
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.lm.sl.spfi.operations.client.model;

import java.util.*;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Activate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-05T15:45:15.451877287Z[GMT]")

public class Activate implements OneOfstatusDetails {
  @SerializedName("externalId")
  private String externalId = null;

  @SerializedName("endpoints")
  private List<Endpoint> endpoints = new ArrayList<Endpoint>();

  @SerializedName("additionalProperties")
  private Map<String, String> additionalProperties = null;

  public Activate externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @Schema(required = true, description = "")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public Activate endpoints(List<Endpoint> endpoints) {
    this.endpoints = endpoints;
    return this;
  }

  public Activate addEndpointsItem(Endpoint endpointsItem) {
    this.endpoints.add(endpointsItem);
    return this;
  }

   /**
   * Get endpoints
   * @return endpoints
  **/
  @Schema(required = true, description = "")
  public List<Endpoint> getEndpoints() {
    return endpoints;
  }

  public void setEndpoints(List<Endpoint> endpoints) {
    this.endpoints = endpoints;
  }

  public Activate additionalProperties(Map<String, String> additionalProperties) {
    this.additionalProperties = additionalProperties;
    return this;
  }

  public Activate addAdditionalPropertiesItem(AdditionalProperty additionalPropertiesItem) {
    if (this.additionalProperties == null) {
      this.additionalProperties = new HashMap<String, String>();
    }
    //this.additionalProperties.put(additionalPropertiesItem);
    return this;
  }

   /**
   * Get additionalProperties
   * @return additionalProperties
  **/
  @Schema(description = "")
  public Map<String, String> getAdditionalProperties() {
    return additionalProperties;
  }

  public void setAdditionalProperties(Map<String,String> additionalProperties) {
    this.additionalProperties = additionalProperties;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Activate activate = (Activate) o;
    return Objects.equals(this.externalId, activate.externalId) &&
        Objects.equals(this.endpoints, activate.endpoints) &&
        Objects.equals(this.additionalProperties, activate.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalId, endpoints, additionalProperties);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Activate {\n");
    
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    endpoints: ").append(toIndentedString(endpoints)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
