/*
 * SaaS Provider Fulfillment Interface API.
 * * SPFI API Design based on \"Notification\", \"Resolve\" and \"Status\" approach * SPFI following the design of Notified Command (write,update,delete,...) and Query (read) Segregation  * It consists of a set of APIs to be invoked/called by SaaS Providers. * This is the lite version of SFPI focuses only Frontrunner applications (Ex:ICEA Bundles).  * Scope limited to tenants in the first release, but extensible to add further entities. 
 *
 * OpenAPI spec version: 1.0.6-sap-dev-internal
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.lm.sl.spfi.operations.client.model;


/**
 * AdditionalProperty
 */

public class AdditionalProperty {

    private String serviceInstanceId;
    private String subscriptionId;
    private String btpSubaccountId;

    public String getServiceInstanceId() {
        return serviceInstanceId;
    }

    public void setServiceInstanceId(String serviceInstanceId) {
        this.serviceInstanceId = serviceInstanceId;
    }

    public String getSubscriptionId() {
        return subscriptionId;
    }

    public void setSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    public String getBtpSubaccountId() {
        return btpSubaccountId;
    }

    public void setBtpSubaccountId(String btpSubaccountId) {
        this.btpSubaccountId = btpSubaccountId;
    }
}
