/*
 * SaaS Provider Fulfillment Interface API.
 * * SPFI API Design based on \"Notification\", \"Resolve\" and \"Status\" approach * SPFI following the design of Notified Command (write,update,delete,...) and Query (read) Segregation  * It consists of a set of APIs to be invoked/called by SaaS Providers. * This is the lite version of SFPI focuses only Frontrunner applications (Ex:ICEA Bundles).  * Scope limited to tenants in the first release, but extensible to add further entities. 
 *
 * OpenAPI spec version: 1.0.6-sap-dev-internal
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.lm.sl.spfi.operations.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * BlockContext
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-05T15:45:15.451877287Z[GMT]")

public class BlockContext implements OneOfSaaSFulfillmentDetails {
  @SerializedName("tenant")
  private BlockContextTenant tenant = null;

  public BlockContext tenant(BlockContextTenant tenant) {
    this.tenant = tenant;
    return this;
  }

   /**
   * Get tenant
   * @return tenant
  **/
  @Schema(required = true, description = "")
  public BlockContextTenant getTenant() {
    return tenant;
  }

  public void setTenant(BlockContextTenant tenant) {
    this.tenant = tenant;
  }

  @SerializedName("additionalProperties")
  private AdditionalProperties additionalProperties = null;

  @Schema(description = "")
  public AdditionalProperties getAdditionalProperties() {
    return additionalProperties;
  }

  public void setAdditionalProperties(AdditionalProperties additionalProperties) {
    this.additionalProperties = additionalProperties;
  }

  public BlockContext additionalProperties(AdditionalProperties additionalProperties) {
    this.additionalProperties = additionalProperties;
    return this;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockContext blockContext = (BlockContext) o;
    return Objects.equals(this.tenant, blockContext.tenant);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenant);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockContext {\n");
    
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
