/*
 * SaaS Provider Fulfillment Interface API.
 * * SPFI API Design based on \"Notification\", \"Resolve\" and \"Status\" approach * SPFI following the design of Notified Command (write,update,delete,...) and Query (read) Segregation  * It consists of a set of APIs to be invoked/called by SaaS Providers. * This is the lite version of SFPI focuses only Frontrunner applications (Ex:ICEA Bundles).  * Scope limited to tenants in the first release, but extensible to add further entities. 
 *
 * OpenAPI spec version: 1.0.6-sap-dev-internal
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.lm.sl.spfi.operations.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * BlockContextTenant
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-05T15:45:15.451877287Z[GMT]")

public class BlockContextTenant {
  @SerializedName("solutionId")
  private String solutionId = null;

  @SerializedName("externalId")
  private String externalId = null;

  @SerializedName("operationType")
  private String operationType = null;

  @SerializedName("spec")
  private TenantSpec spec = null;

  public BlockContextTenant solutionId(String solutionId) {
    this.solutionId = solutionId;
    return this;
  }

   /**
   * Get solutionId
   * @return solutionId
  **/
  @Schema(required = true, description = "")
  public String getSolutionId() {
    return solutionId;
  }

  public void setSolutionId(String solutionId) {
    this.solutionId = solutionId;
  }

  public BlockContextTenant externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @Schema(required = true, description = "")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  // added operationType - upsl-340
  public BlockContextTenant operationType(String operationType) {
    this.operationType = operationType;
    return this;
  }
  /**
   * Get operationType
   * @return operationType
   **/
  @Schema(description = "")
  public String getOperationType() {
    return operationType;
  }

  public void setOperationType(String operationType) {
    this.operationType = operationType;
  }

  //adding spec
  public BlockContextTenant spec(TenantSpec spec) {
    this.spec = spec;
    return this;
  }

  /**
   * Get spec
   * @return spec
   **/
  @Schema(description = "")
  public TenantSpec getSpec() {
    return spec;
  }

  public void setSpec(TenantSpec spec) {
    this.spec = spec;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockContextTenant blockContextTenant = (BlockContextTenant) o;
    return Objects.equals(this.solutionId, blockContextTenant.solutionId) &&
        Objects.equals(this.externalId, blockContextTenant.externalId)&&
            Objects.equals(this.operationType, blockContextTenant.operationType) &&
            Objects.equals(this.spec, blockContextTenant.spec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(solutionId, externalId, operationType, spec);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockContextTenant {\n");
    
    sb.append("    solutionId: ").append(toIndentedString(solutionId)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    operationType: ").append(toIndentedString(operationType)).append("\n");
    sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
