/*
 * SaaS Provider Fulfillment Interface API.
 * * SPFI API Design based on \"Notification\" and \"Resolve\" approach * SPFI following the design of Notified Command (write,update,delete,...)and Query(read) Segregation  * It consists of a set of APIs to be invoked/called by SaaS Providers. * This is the lite version of SFPI focuses only Frontrunner applications(Ex:ICEA Bundles).  * Scope limited to tenants in the first release,but extensible to add further entities. 
 *
 * OpenAPI spec version: 1.0.2-sap-dev-internal
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.lm.sl.spfi.operations.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Customer
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-03-28T15:44:05.391Z[GMT]")
public class Customer {
  @SerializedName("id")
  private String id = null;

  @SerializedName("erpId")
  private String erpId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("contact")
  private CustomerContact contact = null;

  public Customer id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Customer erpId(String erpId) {
    this.erpId = erpId;
    return this;
  }

  /**
   * Get erpId
   * @return erpId
   **/
  @Schema(description = "")
  public String getErpId() {
    return erpId;
  }

  public void setErpId(String erpId) {
    this.erpId = erpId;
  }

  public Customer name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Customer contact(CustomerContact contact) {
    this.contact = contact;
    return this;
  }

   /**
   * Get contact
   * @return contact
  **/
  @Schema(description = "")
  public CustomerContact getContact() {
    return contact;
  }

  public void setContact(CustomerContact contact) {
    this.contact = contact;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Customer customer = (Customer) o;
    return Objects.equals(this.id, customer.id) &&
        Objects.equals(this.erpId, customer.erpId) &&
        Objects.equals(this.name, customer.name) &&
        Objects.equals(this.contact, customer.contact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, erpId, name, contact);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    erpId: ").append(toIndentedString(erpId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
