/*
 * SaaS Provider Fulfillment Interface API.
 * * SPFI API Design based on \"Notification\" and \"Resolve\" approach * SPFI following the design of Notified Command (write,update,delete,...) and Query (read) Segregation  * It consists of a set of APIs to be invoked/called by SaaS Providers. * This is the lite version of SFPI focuses only Frontrunner applications (Ex:ICEA Bundles).  * Scope limited to tenants in the first release, but extensible to add further entities. 
 *
 * OpenAPI spec version: 1.0.3-sap-dev-internal
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.lm.sl.spfi.operations.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * SsosetupApplicationProvider
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-14T12:21:19.417Z[GMT]")
public class SsosetupApplicationProvider {
  @SerializedName("ssoType")
  private String ssoType = null;

  @SerializedName("metadataURL")
  private String metadataURL = null;

  @SerializedName("configName")
  private String configName = null;

  @SerializedName("status")
  private String status = null;

  public SsosetupApplicationProvider ssoType(String ssoType) {
    this.ssoType = ssoType;
    return this;
  }

   /**
   * Get ssoType
   * @return ssoType
  **/
  @Schema(description = "")
  public String getSsoType() {
    return ssoType;
  }

  public void setSsoType(String ssoType) {
    this.ssoType = ssoType;
  }

  public SsosetupApplicationProvider metadataURL(String metadataURL) {
    this.metadataURL = metadataURL;
    return this;
  }

   /**
   * Get metadataURL
   * @return metadataURL
  **/
  @Schema(description = "")
  public String getMetadataURL() {
    return metadataURL;
  }

  public void setMetadataURL(String metadataURL) {
    this.metadataURL = metadataURL;
  }

  public SsosetupApplicationProvider configName(String configName) {
    this.configName = configName;
    return this;
  }

   /**
   * Get configName
   * @return configName
  **/
  @Schema(description = "")
  public String getConfigName() {
    return configName;
  }

  public void setConfigName(String configName) {
    this.configName = configName;
  }

  public SsosetupApplicationProvider status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SsosetupApplicationProvider ssosetupApplicationProvider = (SsosetupApplicationProvider) o;
    return Objects.equals(this.ssoType, ssosetupApplicationProvider.ssoType) &&
        Objects.equals(this.metadataURL, ssosetupApplicationProvider.metadataURL) &&
        Objects.equals(this.configName, ssosetupApplicationProvider.configName) &&
        Objects.equals(this.status, ssosetupApplicationProvider.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ssoType, metadataURL, configName, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SsosetupApplicationProvider {\n");
    
    sb.append("    ssoType: ").append(toIndentedString(ssoType)).append("\n");
    sb.append("    metadataURL: ").append(toIndentedString(metadataURL)).append("\n");
    sb.append("    configName: ").append(toIndentedString(configName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
