/*
 * SaaS Provider Fulfillment Interface API.
 * * SPFI API Design based on \"Notification\" and \"Resolve\" approach * SPFI following the design of Notified Command (write,update,delete,...) and Query (read) Segregation  * It consists of a set of APIs to be invoked/called by SaaS Providers. * This is the lite version of SFPI focuses only Frontrunner applications (Ex:ICEA Bundles).  * Scope limited to tenants in the first release, but extensible to add further entities. 
 *
 * OpenAPI spec version: 1.0.3-sap-dev-internal
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.lm.sl.spfi.operations.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * SsosetupContext
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-14T12:21:19.417Z[GMT]")
public class SsosetupContext implements OneOfSaaSFulfillmentDetails {
  @SerializedName("tenant")
  private SsosetupContextTenant tenant = null;

  @SerializedName("identityProvider")
  private Identityprovider identityProvider = null;

  public SsosetupContext tenant(SsosetupContextTenant tenant) {
    this.tenant = tenant;
    return this;
  }

   /**
   * Get tenant
   * @return tenant
  **/
  @Schema(description = "")
  public SsosetupContextTenant getTenant() {
    return tenant;
  }

  public void setTenant(SsosetupContextTenant tenant) {
    this.tenant = tenant;
  }

  public SsosetupContext identityProvider(Identityprovider identityProvider) {
    this.identityProvider = identityProvider;
    return this;
  }

   /**
   * Get identityProvider
   * @return identityProvider
  **/
  @Schema(description = "")
  public Identityprovider getIdentityProvider() {
    return identityProvider;
  }

  public void setIdentityProvider(Identityprovider identityProvider) {
    this.identityProvider = identityProvider;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SsosetupContext ssosetupContext = (SsosetupContext) o;
    return Objects.equals(this.tenant, ssosetupContext.tenant) &&
        Objects.equals(this.identityProvider, ssosetupContext.identityProvider);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenant, identityProvider);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SsosetupContext {\n");
    
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    identityProvider: ").append(toIndentedString(identityProvider)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
