/*
 * SaaS Provider Fulfillment Interface API.
 * * SPFI API Design based on \"Notification\" and \"Resolve\" approach * SPFI following the design of Notified Command (write,update,delete,...)and Query(read) Segregation  * It consists of a set of APIs to be invoked/called by SaaS Providers. * This is the lite version of SFPI focuses only Frontrunner applications(Ex:ICEA Bundles).  * Scope limited to tenants in the first release,but extensible to add further entities. 
 *
 * OpenAPI spec version: 1.0.2-sap-dev-internal
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.sap.lm.sl.spfi.operations.client.model;

import java.util.List;
import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TenantSpec
 */

public class TenantSpec {
  @SerializedName("region")
  private String region = null;

  @SerializedName("dataCenter")
  private String dataCenter = null;

  @SerializedName("spcDataCenter")
  private String spcDataCenter = null;

  @SerializedName("businessType")
  private String businessType = null;

  @SerializedName("iasUrl")
  private String iasUrl = null;

  @SerializedName("skus")
  private List<String> skus = null;

  @SerializedName("products")
  private List<Product> products;

   /**
   * Get region
   * @return region
  **/
  @Schema(description = "")
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

   /**
   * Get dataCenter
   * @return dataCenter
  **/
  @Schema(description = "")
  public String getDataCenter() {
    return dataCenter;
  }

  public void setDataCenter(String dataCenter) {
    this.dataCenter = dataCenter;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TenantSpec tenantSpec = (TenantSpec) o;
    return Objects.equals(this.region, tenantSpec.region) &&
        Objects.equals(this.dataCenter, tenantSpec.dataCenter);
  }

  // added spc datacenter
  public TenantSpec spcDataCenter(String spcDataCenter) {
    this.spcDataCenter = spcDataCenter;
    return this;
  }

  /**
   * Get spcDataCenter
   * @return spcDataCenter
   **/
  @Schema(description = "")
  public String getSpcDataCenter() {
    return spcDataCenter;
  }

  public void setSpcDataCenter(String spcDataCenter) {
    this.spcDataCenter = spcDataCenter;
  }

  // added skus - upsl-306
  public TenantSpec skus(List<String> skus) {
    this.skus = skus;
    return this;
  }

  /**
   * Get skus
   * @return skus
   **/
  @Schema(description = "")
  public List<String> getSkus() {
    return skus;
  }

  public void setSkus(List<String> skus) {
    this.skus = skus;
  }


  // added products - upsl-340
  public TenantSpec products(List<Product> products) {
    this.products = products;
    return this;
  }
  @Schema(description = "")
  public List<Product> getProducts() {
    return products;
  }

  public void setProducts(List<Product> products) {
    this.products = products;
  }

  @Override
  public int hashCode() {
    return Objects.hash(region, dataCenter);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TenantSpec {\n");
    
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    dataCenter: ").append(toIndentedString(dataCenter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

public String getBusinessType() {
    return businessType;
}

public void setBusinessType(String businessType) {
    this.businessType = businessType;
}

public String getIasUrl() {
    return iasUrl;
}

public void setIasUrl(String iasUrl) {
    this.iasUrl = iasUrl;
}

}
